/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingPageRouteImport } from './routes/_landingPage'
import { Route as LandingPageIndexRouteImport } from './routes/_landingPage/index'

const LandingPageRoute = LandingPageRouteImport.update({
  id: '/_landingPage',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingPageIndexRoute = LandingPageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingPageRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LandingPageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LandingPageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_landingPage': typeof LandingPageRouteWithChildren
  '/_landingPage/': typeof LandingPageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/_landingPage' | '/_landingPage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LandingPageRoute: typeof LandingPageRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_landingPage': {
      id: '/_landingPage'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandingPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landingPage/': {
      id: '/_landingPage/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingPageIndexRouteImport
      parentRoute: typeof LandingPageRoute
    }
  }
}

interface LandingPageRouteChildren {
  LandingPageIndexRoute: typeof LandingPageIndexRoute
}

const LandingPageRouteChildren: LandingPageRouteChildren = {
  LandingPageIndexRoute: LandingPageIndexRoute,
}

const LandingPageRouteWithChildren = LandingPageRoute._addFileChildren(
  LandingPageRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LandingPageRoute: LandingPageRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
